# Print a new line at the start of the prompt
add_newline = true

continuation_prompt = "▶▶"

# Order of modules on prompt
format = """$cmd_duration\
        $line_break\
        $custom\
        $username\
        $hostname\
        $directory\
        (↓ Source control - for right side ↓)\
        $git_branch\
        $git_commit\
        $git_status\
        $git_state\
        (↑ Source control - for right side ↑)\
        $character\
    """

right_format = """$docker_context\
        (↓ Toolchain version modules ↓)\
        $dart\
        $golang\
        $java\
        $nodejs\
        $php\
        $python\
        $rust\
        $swift\
        (↑ Toolchain version modules ↑)\
        (↓ Package modules ↓)\
        $package\
        (↑ Package modules ↑)\
        $env_var\
        $time\
        (↑ above input line ↑)\
        $line_break\
        (↓ on input line ↓)\
        $battery\
        $jobs\
        $status\
        """

# Generic prompt configurations
[character]
success_symbol = ""
error_symbol = "[ X](bold red)"

[line_break]
disabled = true

# Module configurations

[battery]
# disabled = true
full_symbol = ""
charging_symbol = " "
discharging_symbol = " "
unknown_symbol = ""
empty_symbol = ""
format = "[[](bg:#ab1515 fg:black) $symbol$percentage[](bg:black fg:#ab1515)]($style)"
[[battery.display]]
threshold = 10
style = "bold bg:#ab1515 fg:#ffffff"
[[battery.display]]
threshold = 20
style = "bg:#ab1515 fg:#ffffff"

[cmd_duration]
# disabled = true
format = """took [$duration]($style)

"""

[dart]
# disabled = true
symbol = " " # original
# symbol = "﯑ " # clearer
style = "bg:#32BBF9 fg:#111111"
format = "[[](bg:#32BBF9 fg:black) $symbol$version[](bg:black fg:#32BBF9)]($style)"

[directory]
style = "italic bg:#545B68 fg:#EEEEEE"
read_only = "  "
read_only_style = "bold bg:red fg:#ffffff"
# truncation_length = 3
truncate_to_repo = true
# truncation_symbol = "…"
# fish_style_pwd_dir_length = 3
format = "([[](bg:red fg:black)$read_only[](bg:black fg:red)]($read_only_style))[[](bg:#545B68 fg:black) $path [](bg:black fg:#545B68)]($style)"

[directory.substitutions]
"~/Documents" = ""
"~/Music" = ""
"~/Movies" = ""
"~/Pictures" = ""
"~/Sources" = ""
"~" = ""
"/" = "  "

[docker_context]
# disabled = true
symbol = " "
style = "bg:#3A91DC  fg:#EEEEEE"
only_with_files = true
format = "[[](bg:#3A91DC fg:black) $symbol$context [](bg:black fg:#3A91DC)]($style)"

[env_var]
disabled = true
symbol = " "
style = "bg:#545B68 fg:#EEEEEE"
variable = "0"
default = "fish"
format = "([[](bg:#545B68 fg:black) $symbol$env_value [](bg:black fg:#545B68)]($style))"

[git_branch]
# disabled = true
symbol = " "
# symbol = " " # alternate
style = "bg:#96ab5f fg:#111111"
# truncation_length = 4
# truncation_symbol = ""
format = "[[](bg:#96ab5f fg:black) $symbol$branch [](bg:black fg:#96ab5f)]($style)"

[git_commit]
# disabled = true
style = "bg:#E58F73 fg:#111111"
commit_hash_length = 4
# only_detached = true
format = "[[](bg:#E58F73 fg:black) #$hash [](bg:black fg:#E58F73)]($style)"

[git_state]
# disabled = true
style = "bg:#E0B25D fg:111111"
rebase = "rebasing"
merge = "merging"
revert = "reverting"
cherry_pick = " picking"
bisect = "bisecting"
am = "am'ing"
am_or_rebase = "am/rebase"
format = '\([[](bg:#E0B25D fg:black) $state($progress_current/$progress_total) [](bg:black fg:#E0B25D)]($style)\)'

[git_status]
# disabled = true
style = "bg:#E0B25D fg:#000000"
stashed = " ${count}"
ahead = "ﲗ ${count}"
behind = "ﲔ ${count}"
diverged = "D ${ahead_count} ${behind_count}"
conflicted = "${count}"
deleted = " ${count}"
renamed = "﫦${count}"
modified = " M${count}"
staged = "  ${count}"
untracked = "  ${count}"
format = "([[](bg:#E0B25D fg:black) $stashed$staged$modified$renamed$untracked$deleted$conflicted$ahead_behind [](bg:black fg:#E0B25D)]($style))"

[golang]
# disabled = true
symbol = " "
style = "bg:#7FD5EA fg:#111111"
format = "[[](bg:#7FD5EA fg:black) $symbol$version [](bg:black fg:#7FD5EA)]($style)"

[hostname]
# disabled = true
style = "bg:#57686B fg:#111111"
trim_at = "."
format = "[[](bg:#57686B fg:black)($style)$hostname [](bg:black fg:#222A36)]($style)"

[java]
# disabled = true
symbol = " "
style = "bg:#ED8B00 fg:#111111"
format = "[[](bg:#ED8B00 fg:black) $symbol$version [](bg:black fg:#ED8B00)]($style)"

[jobs]
# disabled = true
symbol = "  "
style = "bold bg:black fg:#b4bbc8"
# threshold = 1
format = "[ $symbol$number]($style)"

[kubernetes]
disabled = false
symbol = "☸︎"
style = "bg:#3371E3 fg:#EEEEEE"
format = '[[](bg:#3371E3 fg:black) $symbol$context (\($namespace\))[](bg:black fg:#3371E3)]($style)'

[memory_usage]
disabled = false
symbol = " "
style = "bg:#BBBBBB fg:#111111"
threshold = -1
format = "([[](bg:#BBBBBB fg:black) $symbol$ram (:$swap)[](bg:black fg:#BBBBBB)]($style))"

[nodejs]
# disabled = true
symbol = " "
style = "bg:#005F00 fg:#EEEEEE"
format = "[[](bg:black fg:#005F00) $symbol$version [](bg:#005F00 fg:black)]($style)"

[package]
# disabled = true
symbol = " "
style = "bg:#545B68 fg:#EEEEEE"
display_private = false
format = "[[](bg:#545B68 fg:black) $symbol$version [](bg:black fg:#545B68)]($style)"

[php]
# disabled = true
symbol = " "
style = "bg:#8892BF fg:#EEEEEE"
format = "[[](bg:#8892BF fg:black) $symbol$version [](bg:black fg:#8892BF)]($style)"

[python]
# disabled = true
symbol = " "
style = "bg:#EBD45B fg:#111111"
# pyenv_version_name = true
pyenv_prefix = "pyenv "
python_binary = "python3"
format = '[[](bg:#EBD45B fg:black) $symbol$pyenv_prefix$version(\($virtualenv\)) [](bg:black fg:#EBD45B)]($style)'

[ruby]
# disabled = true
symbol = " "
# symbol = " " # alternate
style = "bg:#CC342D fg:#EEEEEE"
format = "[[](bg:#CC342D fg:black) $symbol$version [](bg:black fg:#CC342D)]($style)"

[rust]
# disabled = true
symbol = " "
# symbol = " " # alternate
style = "bg:#A72145 fg:#EEEEEE"
format = "[[](bg:#A72145 fg:black) $symbol$version [](bg:black fg:#A72145)]($style)"

[swift]
# disabled = true
symbol = "ﯣ "
style = "bg:#F05138 fg:#EEEEEE"
format = "[[](bg:#F05138 fg:black) $symbol$version [](bg:black fg:#F05138)]($style)"

[status]
# disabled = false
symbol = ""
style = "bg:black fg:#FF6E79"
format = "[ $symbol$status]($style)"

[time]
disabled = false
### color is set to orange, because of the configured time_range--to get your attention for e. g. R&R time ;)
style = "bg:#f56942 fg:#111111"
use_12hr = false
time_format = "%H:%M"
utc_time_offset = "local"
time_range = "18:00:00-06:00:00"
format = "[[](bg:black fg:#f56942)  $time [](bg:#f56942 fg:black)]($style)"

[username]
# disabled = true
# show_always = true
style_root = "bold bg:red fg:#DE935F"
style_user = "bg:#728da8 fg:#222A36"
format = "[ \\$ $user [](bg:black fg:red)]($style)"

# Show the local git username if git dir has it set locally
# Show the logged in user if not root
[custom.git_name]
command = 'git config --local user.name || echo $USER'
when = "test $USER != 'root'"
format = "[ \\$ $output [](bg:black fg:#728da8)]($style)"
style = "bg:#728da8 fg:#222A36"

